FROM zulip/docker-zulip:4.3-0 as base

RUN apt-get update && \
    apt-get -q install nano

#COPY custom_zulip_files/871bf3516a4ec8003f2b.css /root/zulip/prod-static/serve/webpack-bundles
#COPY custom_zulip_files/871bf3516a4ec8003f2b.css /home/zulip/prod-static/webpack-bundles
COPY custom_zulip_files/base.html /root/zulip/prod-static/serve/webpack-bundles
COPY custom_zulip_files/portico.html /home/zulip/prod-static/webpack-bundles

RUN sudo service nginx restart
#RUN su zulip -c /home/zulip/deployments/current/scripts/restart-server

EXPOSE 80 443

ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["app:run"]

#docker build --pull --rm -f "Dockerfile_cof" -t dockerzulip:cofidis "." --no-cache
